### ISSUE TITLE
Bill close icon / retract experience

### ISSUE THREAD

**Issue by nanvenomous** [clauseout/tasks#4]
Use [MUI close icon](https://mui.com/material-ui/material-icons/?query=close&selected=Close) at top left of bill card detail screen.
In order for this to work we need a new retract experience. I think this is blocked until we can figure a single page retract experience with on page loading. Looking for some UI/UX direction.

**Comment by cwmunch** [comment]
Not the most direct way to do it, but perhaps what creates the best direct flow would be:
See bill in Agenda, Bill -> Vote -> see new Bill -> Vote. 

To retract vote:
Go to profile and find bill. Hold on bill, dropdown menu like 44 seconds into this video 
https://youtu.be/rQ9eixXeZ4c?si=9dcMXwaBIg0IMyKG

Bit of an anti pattern, but overall best flow

**Comment by nanvenomous** [comment]
> Not the most direct way to do it, but perhaps what creates the best direct flow would be: See bill in Agenda, Bill -> Vote -> see new Bill -> Vote.
> 
> To retract vote: Go to profile and find bill. Hold on bill, dropdown menu like 44 seconds into this video https://youtu.be/rQ9eixXeZ4c?si=9dcMXwaBIg0IMyKG
> 
> Bit of an anti pattern, but overall best flow

Ok, awesome so are we thinking the three dots menu? or will a user know to click the up/down vote icon to get a remove menu:

I could also do a general [indeterminate progress](https://mui.com/material-ui/react-progress/#linear-indeterminate) instead of a custom loading, but in my experience these can be a bit flat when used for too many things.

and then I'm looking for the appropriate mui icon:
- [check done](https://mui.com/material-ui/material-icons/?query=remove&selected=RemoveDone)
- [remove query](https://mui.com/material-ui/material-icons/?query=remove)

If we still want the icon top left then we can use the same loading strategy (circle around the icon).
